version: 0.2

phases:
  #pre_build:
   # commands:
    #  - export ANDROID_HOME=/opt/android-sdk-linux
     # - export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
  build:
    commands:
      - cd android
      - ./gradlew assembleRelease
artifacts:
  files:
     - './android/app/build/outputs/*/.apk'
  discard-paths: yes